name: Build VSIX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      
    - name: Install proto and websockets
      run: npm install ws protobufjs     

    # Package the extension as a VSIX file
    - name: Package VSIX
      run: npx vsce package
      
      # Upload VSIX as a GitHub Release asset
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this
        with:
          tag_name: v1.0.0 # You can use dynamic versioning if needed
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      # Upload VSIX to the release
      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./*.vsix"
          asset_name: "your-extension.vsix"
          asset_content_type: application/octet-stream
          
